from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional

from backend.core.notice_generator import NoticeGenerator
from backend.services.ws_manager import manager

router = APIRouter(prefix="/api/notices", tags=["notices"])


class NoticeRequest(BaseModel):
    noticeType: str = "SCN-MISMATCH"
    gstin: str = "27AADCB2230M1ZT"
    violationType: Optional[str] = None
    amount: Optional[float] = None
    taxpayerName: Optional[str] = "ABC Enterprises"
    period: str = "FY 2023-24"
    demandAmount: float = 250000
    section: str = "73"
    description: Optional[str] = None
    additionalContext: Optional[str] = None
    officer: Optional[str] = None
    noticeContent: Optional[str] = None


@router.post("/generate")
async def generate_notice(req: NoticeRequest):
    gen = NoticeGenerator()
    amount = req.amount or req.demandAmount
    section = req.section
    if req.violationType:
        # Extract section from "Section 73 — Tax Not Paid..."
        parts = req.violationType.split("—")
        if parts:
            sec_part = parts[0].strip().replace("Section ", "")
            if sec_part.isdigit() or "(" in sec_part:
                section = sec_part

    notice = await gen.generate(
        vendor_gstin=req.gstin,
        notice_type=req.noticeType,
        period=req.period,
        amount=amount,
        section=section,
    )
    # Map 'draft' to 'noticeContent' for frontend compatibility
    notice["noticeContent"] = notice.pop("draft", "")
    notice["notice"] = notice["noticeContent"]
    notice["gstin"] = req.gstin
    notice["taxpayerName"] = req.taxpayerName
    notice["demandAmount"] = amount
    notice["description"] = req.description

    try:
        await manager.broadcast(
            "29AAACN0001A1Z5",
            {"type": "NOTICE_READY", "payload": {"noticeId": notice["noticeId"], "vendor": req.gstin}},
        )
    except Exception:
        pass
    return notice


@router.get("/{notice_id}/pdf")
async def download_notice_pdf(notice_id: str):
    """Generate a simple text-based PDF for the notice."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", size=11)
        pdf.cell(0, 10, f"GST Notice: {notice_id}", ln=True, align="C")
        pdf.ln(10)
        pdf.set_font("Helvetica", size=9)
        pdf.multi_cell(0, 6, f"Notice ID: {notice_id}\nGenerated by TaxIQ Notice Generator\n\nThis is a system-generated notice.")
        content = pdf.output()
        return Response(content=content, media_type="application/pdf",
                        headers={"Content-Disposition": f'attachment; filename="notice_{notice_id}.pdf"'})
    except ImportError:
        return {"noticeId": notice_id, "status": "PDF generation requires fpdf2 package."}


@router.post("/{notice_id}/send")
async def send_notice_email(notice_id: str):
    return {"noticeId": notice_id, "status": "sent", "message": "Notice email queued for delivery."}
